name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  merge_group:
    branches: 
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'SoapExtensions.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
